[package]
name = "libsumatracrypt-rs"
authors = ["silene"]
version = "0.1.0"
description = "A Rust Library For Cryptography"
keywords = ["crypto","cryptography","encryption","digest","signature"]
categories = ["cryptography"]
readme = "README.md"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/Silene0259/num-primes"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
new-rand = {package = "rand", version="0.8.5"}

rand = "0.7.3"
ecies-ed25519 = "0.5.1"
rsa = { version = "0.9.6", features = ["sha2","pem"] }

zeroize = "1.8.1"
subtle = "2.6"


# CSPRNG
getrandom = "0.2.14"

# Encoding
base32 = "0.5.0"
hex = "0.4.3"
bs58 = "0.5.1"

# Digest
blake3 = "1.5.1"
blake2-rfc = "0.2.18"
sha2 = "0.10.8"
tiny-keccak = { version = "2.0.2", features = ["sha3","shake"] }

# Signature
schnorrkel = "0.11.4"
ed25519-dalek = "2.0.0-rc.3"
ed448-goldilocks-plus = "0.11.2"

# DH (Key-Exchange)
x448 = "0.6.0"