[package]
name = "sumatracrypt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ecies = {version = "0.2.7", default-features=false, features = ["xchacha20"] }
new-rand = {package = "rand", version="0.8.5"}

rand = "0.7.3"
ecies-ed25519 = "0.5.1"
rsa = { version = "0.9.6", features = ["sha2"] }
zeroize = "1.8.1"

# Encoding
base32 = "0.5.0"
hex = "0.4.3"
bs58 = "0.5.1"

# Digest
blake3 = "1.5.1"
blake2-rfc = "0.2.18"
sha2 = "0.10.8"
tiny-keccak = { version = "2.0.2", features = ["sha3","shake"] }

# Signature
schnorrkel = "0.11.4"