[package]
name = "sumatracrypt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ecies = {version = "0.2.7", default-features=false, features = ["xchacha20"] }
rand = "0.7.3"
ecies-ed25519 = "0.5.1"
zeroize = "1.8.1"
hex = "0.4.3"
bs58 = "0.5.1"